
select * from dbo.INVENTARIO
select * from dbo.RESPONSABLE where ESTATUS = 'ACTIVO'

select CODIGO, DESCRIP, MARCA, MODELO, SERIE, AREA, NOMBRE, FECHA_ING, NOTAS, INVENTARIO.ESTATUS
from dbo.INVENTARIO left join RESPONSABLE on INVENTARIO.ID_RESP = RESPONSABLE.ID_RESP